name: CI-CD # Nome do workflow

on: # Especificação dos eventos que vão disparar o workflow
  workflow_dispatch: # Possibilidade de disparar manualmente
  push: # Push em uma branch
    branches: [ "main" ]
  pull_request: # Pull request em uma branch
    branches: [ "main" ]

jobs: # Lista de jobs que serão executados
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
    - name: Construção da imagem Docker worker
      uses: docker/build-push-action@v5
      with: 
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          fabricioveronez/exemplo-java:${{github.run_number}}
          fabricioveronez/exemplo-java:latest   
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v3
    - uses: azure/k8s-set-context@v4
      with:
         method: kubeconfig
         kubeconfig: ${{ secrets.K8S_CONFIG }}
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v5
      with:
        manifests: |
          ./k8s/deployment.yaml
        images: |
          fabricioveronez/exemplo-java:${{github.run_number}}
                  